#pragma once
#include "PropertyType.h"
#include "LabelSet.h"
#include "EntityID.h"

#include <variant>
#include <memory>

namespace db::test_nodes {

struct TestProperty {
    TestProperty(PropertyTypeID id, std::string value) :_typeID(id), _value(std::move(value)) {}
    TestProperty(PropertyTypeID id, bool value) :_typeID(id), _value(value) {}
    TestProperty(PropertyTypeID id, uint64_t value) :_typeID(id), _value(value) {}
    TestProperty(PropertyTypeID id, double value) :_typeID(id), _value(value) {}

    PropertyTypeID _typeID {};
    std::variant<bool, uint64_t, double, std::string> _value;
};

struct TestNode {
    EntityID _id = 0;
    LabelSet _labelset = {0};
    std::vector<TestProperty> _props;
};

const static inline std::vector<TestNode> NODES = {
    { ._id = 0, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)9622850},
        {1, (std::string)"HSP90AA1 [lysosomal "},
        {2, (bool)0},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9622850"},
        {7, (std::string)"R-HSA-9622850.1"},
        {12, (std::string)"HSP90AA1 [lysosomal "},
    }, },
    { ._id = 1, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)264476},
        {1, (std::string)"HSPA8 [cytosol]"},
        {2, (bool)0},
        {8, (std::string)"REACT_14864"},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-264476"},
        {7, (std::string)"R-HSA-264476.1"},
        {12, (std::string)"HSPA8 [cytosol]"},
    }, },
    { ._id = 2, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)10007478},
        {1, (std::string)"HSPA8 [cytosol]"},
        {2, (bool)0},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Canis familiaris"},
        {6, (std::string)"R-CFA-264476"},
        {7, (std::string)"R-CFA-264476.1"},
        {12, (std::string)"HSPA8 [cytosol]"},
    }, },
    { ._id = 3, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)10161710},
        {1, (std::string)"HSPA8 [cytosol]"},
        {2, (bool)0},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Sus scrofa"},
        {6, (std::string)"R-SSC-264476"},
        {7, (std::string)"R-SSC-264476.1"},
        {12, (std::string)"HSPA8 [cytosol]"},
    }, },
    { ._id = 4, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)10797189},
        {1, (std::string)"HSP90AA1 [cytosol]"},
        {2, (bool)0},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Plasmodium falciparum"},
        {6, (std::string)"R-PFA-192864-2"},
        {7, (std::string)"R-PFA-192864-2.1"},
        {12, (std::string)"HSP90AA1 [cytosol]"},
    }, },
    { ._id = 5, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)10797187},
        {1, (std::string)"HSP90AA1 [cytosol]"},
        {2, (bool)0},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Plasmodium falciparum"},
        {6, (std::string)"R-PFA-192864"},
        {7, (std::string)"R-PFA-192864.1"},
        {12, (std::string)"HSP90AA1 [cytosol]"},
    }, },
    { ._id = 6, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)9631104},
        {1, (std::string)"HSPA8 [late endosome"},
        {2, (bool)0},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9631104"},
        {7, (std::string)"R-HSA-9631104.1"},
        {12, (std::string)"HSPA8 [late endosome"},
    }, },
    { ._id = 7, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)179837},
        {1, (std::string)"EGFR [plasma membran"},
        {2, (bool)0},
        {8, (std::string)"REACT_9911"},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-179837"},
        {7, (std::string)"R-HSA-179837.1"},
    }, },
    { ._id = 8, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)10079661},
        {1, (std::string)"EGFR [plasma membran"},
        {2, (bool)0},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Bos taurus"},
        {6, (std::string)"R-BTA-179837"},
        {7, (std::string)"R-BTA-179837.1"},
        {12, (std::string)"EGFR [plasma membran"},
    }, },
    { ._id = 9, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)199416},
        {1, (std::string)"AKT1 [plasma membran"},
        {2, (bool)0},
        {8, (std::string)"REACT_13144"},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-199416"},
        {7, (std::string)"R-HSA-199416.1"},
        {12, (std::string)"AKT1 [plasma membran"},
    }, },
    { ._id = 10, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)10680131},
        {1, (std::string)"AKT1 [plasma membran"},
        {2, (bool)0},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Dictyostelium discoi"},
        {6, (std::string)"R-DDI-199416-2"},
        {7, (std::string)"R-DDI-199416-2.1"},
        {12, (std::string)"AKT1 [plasma membran"},
    }, },
    { ._id = 11, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)936508},
        {1, (std::string)"HSPA8 [plasma membra"},
        {2, (bool)0},
        {8, (std::string)"REACT_24811"},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-936508"},
        {7, (std::string)"R-HSA-936508.1"},
        {12, (std::string)"HSPA8 [plasma membra"},
    }, },
    { ._id = 12, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)201600},
        {1, (std::string)"VIM [cytosol]"},
        {2, (bool)0},
        {8, (std::string)"REACT_13917"},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-201600"},
        {7, (std::string)"R-HSA-201600.1"},
        {12, (std::string)"VIM [cytosol]"},
    }, },
    { ._id = 13, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)10084283},
        {1, (std::string)"VIM [cytosol]"},
        {2, (bool)0},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Bos taurus"},
        {6, (std::string)"R-BTA-350314"},
        {7, (std::string)"R-BTA-350314.1"},
        {12, (std::string)"VIM [cytosol]"},
    }, },
    { ._id = 14, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)10451456},
        {1, (std::string)"HSP90AA1 [plasma mem"},
        {2, (bool)0},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Gallus gallus"},
        {6, (std::string)"R-GGA-534996"},
        {7, (std::string)"R-GGA-534996.1"},
        {12, (std::string)"HSP90AA1 [plasma mem"},
    }, },
    { ._id = 15, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)5082380},
        {1, (std::string)"HSPA8 [nucleoplasm]"},
        {2, (bool)0},
        {8, (std::string)"REACT_264752"},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-5082380"},
        {7, (std::string)"R-HSA-5082380.1"},
        {12, (std::string)"HSPA8 [nucleoplasm]"},
    }, },
    { ._id = 16, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)9711070},
        {1, (std::string)"APOE-4 [extracellula"},
        {2, (bool)0},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9711070"},
        {7, (std::string)"R-HSA-9711070.1"},
        {12, (std::string)"APOE-4 [extracellula"},
    }, },
    { ._id = 17, ._labelset = {4,5,}, ._props = {
        {0, (uint64_t)9622845},
        {1, (std::string)"HSP90AA1, HSP90AB1 ["},
        {2, (bool)0},
        {4, (std::string)"DefinedSet"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9622845"},
        {7, (std::string)"R-HSA-9622845.1"},
        {12, (std::string)"HSP90AA1, HSP90AB1 ["},
    }, },
    { ._id = 18, ._labelset = {6,5,}, ._props = {
        {0, (uint64_t)3299408},
        {1, (std::string)"HSP70 proteins [cyto"},
        {2, (bool)0},
        {4, (std::string)"CandidateSet"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-3299408"},
        {7, (std::string)"R-HSA-3299408.1"},
        {12, (std::string)"HSP70 proteins [cyto"},
    }, },
    { ._id = 19, ._labelset = {4,5,}, ._props = {
        {0, (uint64_t)6797275},
        {1, (std::string)"HSPA8, ALOX15 [cytos"},
        {2, (bool)0},
        {4, (std::string)"DefinedSet"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-6797275"},
        {7, (std::string)"R-HSA-6797275.1"},
        {12, (std::string)"HSPA8, ALOX15 [cytos"},
    }, },
    { ._id = 20, ._labelset = {7,}, ._props = {
        {0, (uint64_t)9626246},
        {1, (std::string)"HSPA8:LAMP2a multime"},
        {2, (bool)0},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9626246"},
        {7, (std::string)"R-HSA-9626246.1"},
        {12, (std::string)"HSPA8:LAMP2a multime"},
    }, },
    { ._id = 21, ._labelset = {7,}, ._props = {
        {0, (uint64_t)9615717},
        {1, (std::string)"HSPA8 bound autophag"},
        {2, (bool)0},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9615717"},
        {7, (std::string)"R-HSA-9615717.1"},
        {12, (std::string)"HSPA8 bound autophag"},
    }, },
    { ._id = 22, ._labelset = {7,}, ._props = {
        {0, (uint64_t)9613533},
        {1, (std::string)"p-PLINs:HSPA8 [lipid"},
        {2, (bool)0},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9613533"},
        {7, (std::string)"R-HSA-9613533.1"},
        {12, (std::string)"p-PLINs:HSPA8 [lipid"},
    }, },
    { ._id = 23, ._labelset = {7,}, ._props = {
        {0, (uint64_t)9620192},
        {1, (std::string)"p-PLINs:HSPA8 [cytos"},
        {2, (bool)0},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9620192"},
        {7, (std::string)"R-HSA-9620192.1"},
        {12, (std::string)"p-PLINs:HSPA8 [cytos"},
    }, },
    { ._id = 24, ._labelset = {7,}, ._props = {
        {0, (uint64_t)9613350},
        {1, (std::string)"PLINs:HSPA8 [lipid d"},
        {2, (bool)0},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9613350"},
        {7, (std::string)"R-HSA-9613350.1"},
        {12, (std::string)"PLINs:HSPA8 [lipid d"},
    }, },
    { ._id = 25, ._labelset = {7,}, ._props = {
        {0, (uint64_t)5251937},
        {1, (std::string)"HSPA8:ATP [cytosol]"},
        {2, (bool)0},
        {8, (std::string)"REACT_356892"},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-5251937"},
        {7, (std::string)"R-HSA-5251937.1"},
        {12, (std::string)"HSPA8:ATP [cytosol]"},
    }, },
    { ._id = 26, ._labelset = {7,}, ._props = {
        {0, (uint64_t)5251932},
        {1, (std::string)"HSPA8:ADP [cytosol]"},
        {2, (bool)0},
        {8, (std::string)"REACT_356983"},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-5251932"},
        {7, (std::string)"R-HSA-5251932.1"},
        {12, (std::string)"HSPA8:ADP [cytosol]"},
    }, },
    { ._id = 27, ._labelset = {7,}, ._props = {
        {0, (uint64_t)445018},
        {1, (std::string)"CHL1:HSP7C [plasma m"},
        {2, (bool)0},
        {8, (std::string)"REACT_22887"},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-445018"},
        {7, (std::string)"R-HSA-445018.1"},
        {12, (std::string)"CHL1:HSP7C [plasma m"},
    }, },
    { ._id = 28, ._labelset = {7,}, ._props = {
        {0, (uint64_t)450623},
        {1, (std::string)"AUF1 Complexed with "},
        {2, (bool)0},
        {8, (std::string)"REACT_25605"},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-450623"},
        {7, (std::string)"R-HSA-450623.2"},
        {12, (std::string)"AUF1 Complexed with "},
    }, },
    { ._id = 29, ._labelset = {7,}, ._props = {
        {0, (uint64_t)351175},
        {1, (std::string)"HSC70:Auxillin Compl"},
        {2, (bool)0},
        {8, (std::string)"REACT_15197"},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-351175"},
        {7, (std::string)"R-HSA-351175.1"},
        {12, (std::string)"HSC70:Auxillin Compl"},
    }, },
    { ._id = 30, ._labelset = {8,}, ._props = {
        {0, (uint64_t)9626253},
        {1, (std::string)"HSPA8 binds LAMP2a m"},
        {9, (bool)0},
        {2, (bool)0},
        {10, (std::string)"True"},
        {11, (std::string)"2019-06-12"},
        {4, (std::string)"Reaction"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9626253"},
        {7, (std::string)"R-HSA-9626253.3"},
        {12, (std::string)"HSPA8 binds LAMP2a m"},
    }, },
    { ._id = 31, ._labelset = {8,}, ._props = {
        {0, (uint64_t)9615721},
        {1, (std::string)"HSPA8 binds substrate"},
        {9, (bool)0},
        {2, (bool)0},
        {10, (std::string)"True"},
        {11, (std::string)"2019-06-12"},
        {4, (std::string)"Reaction"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9615721"},
        {7, (std::string)"R-HSA-9615721.4"},
        {12, (std::string)"HSPA8 binds substrate"},
    }, },
    { ._id = 32, ._labelset = {8,}, ._props = {
        {0, (uint64_t)9613352},
        {1, (std::string)"PLINs bind HSPA8"},
        {9, (bool)0},
        {2, (bool)0},
        {10, (std::string)"True"},
        {11, (std::string)"2019-06-12"},
        {4, (std::string)"Reaction"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9613352"},
        {7, (std::string)"R-HSA-9613352.3"},
        {12, (std::string)"PLINs bind HSPA8"},
    }, },
    { ._id = 33, ._labelset = {8,}, ._props = {
        {0, (uint64_t)445087},
        {1, (std::string)"CHL1 interacts with "},
        {9, (bool)0},
        {2, (bool)0},
        {10, (std::string)"True"},
        {8, (std::string)"REACT_22427"},
        {11, (std::string)"2010-06-15"},
        {4, (std::string)"Reaction"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-445087"},
        {7, (std::string)"R-HSA-445087.1"},
        {12, (std::string)"CHL1 interacts with "},
    }, },
    { ._id = 34, ._labelset = {8,}, ._props = {
        {0, (uint64_t)450551},
        {1, (std::string)"AUF1 binds translati"},
        {9, (bool)0},
        {2, (bool)0},
        {10, (std::string)"False"},
        {8, (std::string)"REACT_25267"},
        {11, (std::string)"2010-09-21"},
        {4, (std::string)"Reaction"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-450551"},
        {7, (std::string)"R-HSA-450551.2"},
        {12, (std::string)"AUF1 binds translati"},
    }, },
    { ._id = 35, ._labelset = {8,}, ._props = {
        {0, (uint64_t)9626235},
        {1, (std::string)"HSPA8 dissociates fr"},
        {9, (bool)0},
        {2, (bool)0},
        {10, (std::string)"True"},
        {11, (std::string)"2019-06-12"},
        {4, (std::string)"Reaction"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9626235"},
        {7, (std::string)"R-HSA-9626235.2"},
        {12, (std::string)"HSPA8 dissociates fr"},
    }, },
    { ._id = 36, ._labelset = {8,}, ._props = {
        {0, (uint64_t)9622840},
        {1, (std::string)"HSPA8 dissociates fr"},
        {9, (bool)0},
        {2, (bool)0},
        {10, (std::string)"True"},
        {11, (std::string)"2019-06-12"},
        {4, (std::string)"Reaction"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9622840"},
        {7, (std::string)"R-HSA-9622840.2"},
        {12, (std::string)"HSPA8 dissociates fr"},
    }, },
    { ._id = 37, ._labelset = {9,10,}, ._props = {
        {0, (uint64_t)8868656},
        {1, (std::string)"ATP hydrolysis activ"},
        {4, (std::string)"CatalystActivity"},
        {12, (std::string)"ATP hydrolysis activ"},
    }, },
    { ._id = 38, ._labelset = {9,10,}, ._props = {
        {0, (uint64_t)10058133},
        {1, (std::string)"ATP hydrolysis activ"},
        {4, (std::string)"CatalystActivity"},
        {12, (std::string)"ATP hydrolysis activ"},
    }, },
    { ._id = 39, ._labelset = {9,10,}, ._props = {
        {0, (uint64_t)10215186},
        {1, (std::string)"ATP hydrolysis activ"},
        {5, (std::string)"No species"},
        {4, (std::string)"CatalystActivity"},
        {12, (std::string)"ATP hydrolysis activ"},
    }, },
    { ._id = 40, ._labelset = {0,1,2,3,}, ._props = {
        {0, (uint64_t)192864},
        {1, (std::string)"HSP90AA1 [cytosol]"},
        {2, (bool)0},
        {8, (std::string)"REACT_9878"},
        {3, (std::string)"ReferenceGeneProduct"},
        {4, (std::string)"EntityWithAccessione"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-192864"},
        {7, (std::string)"R-HSA-192864.1"},
        {12, (std::string)"HSP90AA1 [cytosol]"},
    }, },
    { ._id = 41, ._labelset = {7,}, ._props = {
        {0, (uint64_t)9631103},
        {1, (std::string)"HSPA8 bound autophag"},
        {2, (bool)0},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9631103"},
        {7, (std::string)"R-HSA-9631103.1"},
        {12, (std::string)"HSPA8 bound autophag"},
    }, },
    { ._id = 42, ._labelset = {4,5,}, ._props = {
        {0, (uint64_t)9610864},
        {1, (std::string)"HCMV Host Cell Recep"},
        {2, (bool)0},
        {4, (std::string)"DefinedSet"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9610864"},
        {7, (std::string)"R-HSA-9610864.1"},
        {12, (std::string)"HCMV Host Cell Recep"},
    }, },
    { ._id = 43, ._labelset = {7,}, ._props = {
        {0, (uint64_t)179847},
        {1, (std::string)"EGF:EGFR [plasma mem"},
        {2, (bool)0},
        {8, (std::string)"REACT_9893"},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-179847"},
        {7, (std::string)"R-HSA-179847.1"},
        {12, (std::string)"EGF:EGFR [plasma mem"},
    }, },
    { ._id = 44, ._labelset = {7,}, ._props = {
        {0, (uint64_t)9624419},
        {1, (std::string)"EGFR:EGF-like ligand"},
        {2, (bool)0},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9624419"},
        {7, (std::string)"R-HSA-9624419.1"},
        {12, (std::string)"EGFR:EGF-like ligand"},
    }, },
    { ._id = 45, ._labelset = {7,}, ._props = {
        {0, (uint64_t)8857547},
        {1, (std::string)"HBEGF:EGFR [plasma m"},
        {2, (bool)0},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-8857547"},
        {7, (std::string)"R-HSA-8857547.1"},
        {12, (std::string)"HBEGF:EGFR [plasma m"},
    }, },
    { ._id = 46, ._labelset = {7,}, ._props = {
        {0, (uint64_t)9674862},
        {1, (std::string)"EGFR:AAMP [plasma me"},
        {2, (bool)0},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9674862"},
        {7, (std::string)"R-HSA-9674862.1"},
        {12, (std::string)"EGFR:AAMP [plasma me"},
    }, },
    { ._id = 47, ._labelset = {7,}, ._props = {
        {0, (uint64_t)445016},
        {1, (std::string)"L1-EGFR trans-hetero"},
        {2, (bool)0},
        {8, (std::string)"REACT_22956"},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-445016"},
        {7, (std::string)"R-HSA-445016.1"},
        {12, (std::string)"L1-EGFR trans-hetero"},
    }, },
    { ._id = 48, ._labelset = {7,}, ._props = {
        {0, (uint64_t)1248675},
        {1, (std::string)"EGFR:Cetuximab [plas"},
        {2, (bool)0},
        {8, (std::string)"REACT_117571"},
        {4, (std::string)"Complex"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-1248675"},
        {7, (std::string)"R-HSA-1248675.2"},
        {12, (std::string)"EGFR:Cetuximab [plas"},
    }, },
    { ._id = 49, ._labelset = {8,}, ._props = {
        {0, (uint64_t)177942},
        {1, (std::string)"EGFR binds EGF ligand"},
        {2, (bool)0},
        {10, (std::string)"False"},
        {8, (std::string)"REACT_9481"},
        {11, (std::string)"2007-02-20"},
        {4, (std::string)"Reaction"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-177942"},
        {7, (std::string)"R-HSA-177942.4"},
        {12, (std::string)"EGFR binds EGF ligand"},
    }, },
    { ._id = 50, ._labelset = {11,12,13,}, ._props = {
        {0, (uint64_t)2179387},
        {1, (std::string)"Mature HBEGF binds t"},
        {9, (bool)0},
        {2, (bool)0},
        {10, (std::string)"False"},
        {8, (std::string)"REACT_121381"},
        {11, (std::string)"2012-06-12"},
        {4, (std::string)"BlackBoxEvent"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-2179387"},
        {7, (std::string)"R-HSA-2179387.1"},
    }, },
    { ._id = 51, ._labelset = {8,}, ._props = {
        {0, (uint64_t)9674531},
        {1, (std::string)"AAMP binds EGFR"},
        {9, (bool)0},
        {2, (bool)0},
        {10, (std::string)"False"},
        {11, (std::string)"2020-03-17"},
        {4, (std::string)"Reaction"},
        {5, (std::string)"Homo sapiens"},
        {6, (std::string)"R-HSA-9674531"},
        {7, (std::string)"R-HSA-9674531.1"},
        {12, (std::string)"AAMP binds EGFR"},
    }, }
};

const static inline PropertyTypeInfos PROPERTY_TYPE_INFOS {
    {0, {._type = ValueType::UInt64, ._count = 52}},
    {1, {._type = ValueType::String, ._count = 52}},
    {2, {._type = ValueType::Bool, ._count = 49}},
    {3, {._type = ValueType::String, ._count = 18}},
    {4, {._type = ValueType::String, ._count = 52}},
    {5, {._type = ValueType::String, ._count = 49}},
    {6, {._type = ValueType::String, ._count = 49}},
    {7, {._type = ValueType::String, ._count = 49}},
    {8, {._type = ValueType::String, ._count = 19}},
    {9, {._type = ValueType::Bool, ._count = 9}},
    {10, {._type = ValueType::String, ._count = 10}},
    {11, {._type = ValueType::String, ._count = 10}},
    {12, {._type = ValueType::String, ._count = 51}},
};

}

