"""Shared constants for the code review system."""

# Directories to skip
SKIP_DIRS = {"external", "third_party", "build", ".git", "googletest", "test"}

# File patterns to skip
SKIP_FILES = {"test_violations.h", "test_violations.cpp"}

# File extensions to check
CPP_EXTENSIONS = {".cpp", ".h", ".hpp", ".cc", ".cxx"}

# Threshold for code density warning
DENSITY_THRESHOLD = 15

# Known external library prefixes (angle bracket includes)
EXTERNAL_LIBS = {
    "spdlog",
    "nlohmann",
    "crow",
    "antlr4",
    "gtest",
    "gmock",
    "faiss",
    "aws",
    "boost",
    "fmt",
    "rapidjson",
    "tbb",
    "linenoise",
    "tabulate",
    "argparse",
    "termcolor",
    "range",
}

# Known standard library headers
STD_HEADERS = {
    # C headers
    "assert.h",
    "ctype.h",
    "errno.h",
    "float.h",
    "limits.h",
    "locale.h",
    "math.h",
    "setjmp.h",
    "signal.h",
    "stdarg.h",
    "stddef.h",
    "stdio.h",
    "stdlib.h",
    "string.h",
    "time.h",
    "wchar.h",
    "wctype.h",
    "complex.h",
    "fenv.h",
    "inttypes.h",
    "stdbool.h",
    "stdint.h",
    "tgmath.h",
    "uchar.h",
    # C++ wrapper headers (C headers with c prefix) - NOTE: these are discouraged,
    # prefer the .h versions (e.g., <stdint.h> instead of <cstdint>)
    "cassert",
    "cctype",
    "cerrno",
    "cfloat",
    "climits",
    "clocale",
    "cmath",
    "csetjmp",
    "csignal",
    "cstdarg",
    "cstddef",
    "cstdio",
    "cstdlib",
    "cstring",
    "ctime",
    "cwchar",
    "cwctype",
    "ccomplex",
    "cfenv",
    "cinttypes",
    "cstdbool",
    "cstdint",
    "ctgmath",
    "cuchar",
    # POSIX/System headers
    "unistd.h",
    "fcntl.h",
    "pthread.h",
    "dirent.h",
    "dlfcn.h",
    "sys/types.h",
    "sys/stat.h",
    "sys/wait.h",
    "sys/mman.h",
    "sys/socket.h",
    "sys/epoll.h",
    "sys/event.h",
    "sys/signalfd.h",
    "sys/proc_info.h",
    "sys/time.h",
    "sys/resource.h",
    "sys/ioctl.h",
    "sys/uio.h",
    "sys/un.h",
    "sys/select.h",
    "sys/poll.h",
    "netinet/in.h",
    "netinet/tcp.h",
    "netinet/ip.h",
    "arpa/inet.h",
    "net/if.h",
    "netdb.h",
    # macOS specific
    "libproc.h",
    "mach/mach.h",
    "mach/mach_time.h",
    # Compiler intrinsics (x86, ARM, etc.)
    "immintrin.h",
    "emmintrin.h",
    "xmmintrin.h",
    "pmmintrin.h",
    "smmintrin.h",
    "nmmintrin.h",
    "ammintrin.h",
    "avxintrin.h",
    "avx2intrin.h",
    "arm_neon.h",
    # C++ headers
    "algorithm",
    "any",
    "array",
    "atomic",
    "barrier",
    "bit",
    "bitset",
    "charconv",
    "chrono",
    "codecvt",
    "compare",
    "complex",
    "concepts",
    "condition_variable",
    "coroutine",
    "deque",
    "exception",
    "execution",
    "expected",
    "filesystem",
    "format",
    "forward_list",
    "fstream",
    "functional",
    "future",
    "initializer_list",
    "iomanip",
    "ios",
    "iosfwd",
    "iostream",
    "istream",
    "iterator",
    "latch",
    "limits",
    "list",
    "locale",
    "map",
    "memory",
    "memory_resource",
    "mutex",
    "new",
    "numbers",
    "numeric",
    "optional",
    "ostream",
    "queue",
    "random",
    "ranges",
    "ratio",
    "regex",
    "scoped_allocator",
    "semaphore",
    "set",
    "shared_mutex",
    "source_location",
    "span",
    "spanstream",
    "sstream",
    "stack",
    "stacktrace",
    "stdexcept",
    "stop_token",
    "streambuf",
    "string",
    "string_view",
    "strstream",
    "syncstream",
    "system_error",
    "thread",
    "tuple",
    "type_traits",
    "typeindex",
    "typeinfo",
    "unordered_map",
    "unordered_set",
    "utility",
    "valarray",
    "variant",
    "vector",
    "version",
}

# STL containers that should not be returned by value
STL_CONTAINERS = {
    "vector",
    "map",
    "unordered_map",
    "set",
    "unordered_set",
    "list",
    "deque",
    "forward_list",
    "multimap",
    "unordered_multimap",
    "multiset",
    "unordered_multiset",
    "stack",
    "queue",
    "priority_queue",
    "string",
    "wstring",
    "basic_string",
    "string_view",
    # Note: span is excluded - it's a lightweight non-owning view
    # Note: array is excluded - it's fixed-size and trivially copyable
}

# Result type patterns - classes designed to be returned by value
RESULT_TYPE_PATTERNS = {
    "Result",
    "Error",
    "Status",
    "Optional",
    "Expected",
    "Outcome",
    "Maybe",
    "Either",
    "Try",
    "Response",
}

# C++ wrapper headers mapped to their preferred C-style equivalents
# Per CODING_STYLE.md: use <stdlib.h> style, not <cstdlib>
CPP_TO_C_HEADERS = {
    "cassert": "assert.h",
    "ccomplex": "complex.h",
    "cctype": "ctype.h",
    "cerrno": "errno.h",
    "cfenv": "fenv.h",
    "cfloat": "float.h",
    "cinttypes": "inttypes.h",
    "climits": "limits.h",
    "clocale": "locale.h",
    "cmath": "math.h",
    "csetjmp": "setjmp.h",
    "csignal": "signal.h",
    "cstdarg": "stdarg.h",
    "cstdbool": "stdbool.h",
    "cstddef": "stddef.h",
    "cstdint": "stdint.h",
    "cstdio": "stdio.h",
    "cstdlib": "stdlib.h",
    "cstring": "string.h",
    "ctgmath": "tgmath.h",
    "ctime": "time.h",
    "cuchar": "uchar.h",
    "cwchar": "wchar.h",
    "cwctype": "wctype.h",
}
