#pragma once

#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"

#include "DBOps.h"
#include "NLOps.h"

namespace db {

class GraphView;
class Procedure;
class ProcedureManager;

// Lowers a function in the db dialect into a function in the nl dialect.
//
// The db dialect describes a query as column dataflow: db.scan_nodes
// produces a column, each db.get_out_edges consumes columns and produces more,
// and db.output names the result projection.
//
// The nl dialect makes execution explicit: every column becomes a column chunk
// generated by an nl.for loop. Every db op that produces columns
// becomes an nl iterator wrapped in a for loop.
//
// Lowering turns the flat db dataflow into a loop nest:
//
//   db.scan_nodes / db.get_out_edges  ->  nl source op + nl.for over its chunks
//   db.output                          ->  nl.output inside the binding loop
//   db.limit                           ->  a hoisted nl.limit handle, a `limit`
//                                          operand on the loops that produce its
//                                          columns, an nl.limit_update, and an
//                                          nl.limit_truncate that copies the prefix
//                                          just before the consumer (nl.output when
//                                          unchained, the inner query when chained)
//   db.skip                            ->  a hoisted nl.skip handle, an
//                                          nl.skip_update, and an nl.skip_truncate
//                                          that lifts the surviving suffix just
//                                          before the consumer. No loop operand (a
//                                          skip cannot early-exit). When unchained,
//                                          the truncate folds into a skip-bearing
//                                          nl.output that emits the suffix in place
//                                          at an offset; the copy survives only for
//                                          a chained suffix (reads from row zero)
//   db.remove_duplicates               ->  a hoisted nl.distinct seen-set handle
//                                          and an nl.distinct_filter in the
//                                          producing loop body that emits each
//                                          step's not-yet-seen rows as fresh chunks.
//                                          A streaming filter, not a pipeline
//                                          breaker: it stays in the producing loop
//                                          (no emit loop like db.sort), so a
//                                          downstream LIMIT bounds the loop through
//                                          the ordinary early-exit, and a chained
//                                          WITH DISTINCT feeds the survivor chunks
//                                          straight into the next traversal
//   db.count                           ->  a hoisted nl.count tally, an
//                                          nl.count_update in the producing loop
//                                          body that charges each chunk's non-null
//                                          rows, and - after the loop - an
//                                          nl.count_result that materializes the
//                                          single tally row (an unsigned i64,
//                                          !nl.chunk<ui64>) which a function-scope
//                                          nl.output emits. A pipeline breaker like
//                                          db.sort (the count is final only once
//                                          every row is seen), but it collapses to
//                                          one row, so it opens no emit loop
//   db.sum / db.min / db.max / db.avg  ->  the value-reducing siblings of db.count: a
//                                          hoisted nl.aggregate accumulator, an
//                                          nl.aggregate_update in the producing loop
//                                          body that folds each chunk's non-null
//                                          values, and - after the loop - an
//                                          nl.aggregate_result that materializes the
//                                          single reduced row (a nullable value chunk)
//                                          which a function-scope nl.output emits.
//                                          Same pipeline-breaker, one-row shape as
//                                          db.count; one db op per reduction, each
//                                          carrying its nl.aggregate kind
//
// db.get_node_properties / db.get_edge_properties resolve their property name
// against the graph schema here (hence the GraphView): the name is hoisted into
// one nl.get_property_type above the loops, and the concrete value type is baked
// into the nullable value chunk the fetch produces inside the binding loop.
//
// db.hash_join lowers to two sibling loop nests instead: an nl.hash_join_buffer
// hoisted to the top of the block they are rooted in, the right (built) factor's
// nest filling it through an nl.hash_join_collect, and the left (probed) factor's
// nest behind it, bridged by an nl.hash_join_probe that answers each probe row
// with the build rows its key matches. The memory is O(build side) rather than
// bounded, and the build side is read once rather than once per outer chunk.
//
// db.cross_product lowers to two nested factor loop nests - the inner factor's
// loops nested inside the outer factor's innermost loop body, so the inner
// factor re-runs once per outer chunk (a nested-loop join, bounded memory) -
// bridged at the deepest point by an nl.cross_product that crosses the two
// factors' yielded chunks just before db.output consumes them. A factor may
// itself be a db.cross_product (the three-way MATCH (a), (b), (c)): the product
// stands in for that factor's innermost loop, so the enclosing factor nests
// under it and the two products compose into one deeper loop nest.
//
class DBLowering {
public:
    DBLowering(mlir::MLIRContext* context,
               const GraphView* view,
               const ProcedureManager* procedures = nullptr);
    ~DBLowering();

    // Translate a FuncOp in db dialect to nl dialect
    mlir::func::FuncOp lower(mlir::func::FuncOp dbFunction, mlir::ModuleOp module);

private:
    mlir::OpBuilder _builder;

    // Graph schema, used to resolve a property name to its value type
    const GraphView* _view {nullptr};

    // Procedure registry, used to resolve a db.call_procedure's name to the
    // procedure and its declared argument and return types - the procedure
    // counterpart of _view. Null when the caller runs without procedures, which
    // only a module containing a db.call_procedure notices.
    const ProcedureManager* _procedures {nullptr};

    // db column SSA value -> the nl chunk, and a db.distinct_set -> the nl.distinct
    // handle the branches of a union share
    llvm::DenseMap<mlir::Value, mlir::Value> _valueMap;

    // Property name -> the hoisted nl.get_property_type handle, so a name is
    // resolved once and shared by every fetch that reads it
    llvm::StringMap<mlir::Value> _propertyTypes;

    // Edge type names -> the hoisted nl.get_edge_type_set handle, so a set is resolved
    // once and shared by every by-type edge hop that reads it (the edge sibling of
    // _propertyTypes). Keyed on the ArrayAttr, which MLIR uniques, so two hops naming
    // the same types in the same order find the same handle; a different order hoists
    // a second handle for the same set, which costs a resolve and no correctness
    llvm::DenseMap<mlir::Attribute, mlir::Value> _edgeTypeSets;

    // Entry block of the nl function being built
    mlir::Block* _entryBlock {nullptr};

    // The last constant hoisted to the entry block, which the next one goes after. Null
    // while the block opens on something else, where the next constant goes to the top
    mlir::Operation* _lastHoistedConstant {nullptr};

    // The block a root scan opens its loop in. It is the entry block at top
    // level, but a db.cross_product lowers its inner factor with the outer
    // factor's innermost loop body as the root, so the inner factor's scans
    // nest inside the outer loop (the nested-loop join). A pipeline breaker hoists
    // its accumulator here too, so one inside a subquery body run one row at a time
    // resets once per row of that body's loop.
    mlir::Block* _rootBlock {nullptr};

    // The body of the most recent loop buildLoopForSource opened. A factor's
    // dataflow is linear and each loop nests inside the previous, so the last
    // loop opened is the factor's innermost one; lowerFactor reads this once the
    // factor is lowered to root the inner factor there and to place the cross
    // product at that deepest point. Not an insertion cursor - the builder is
    // not left in the loop body - just a record of which block is innermost.
    mlir::Block* _innermostLoopBody {nullptr};

    // Defines the cardinality of the innermost loop, used for projection
    mlir::Value _innermostCardinality;

    // Each db.limit gets its own hoisted nl.limit handle - N independent budgets.
    // A pre-scan in lower() finds every db.limit before any loop is built, so the
    // handles exist first to be threaded into the loops as they are created. The
    // count is unsigned end to end (UI64Attr accessor -> NLLimitState's size_t),
    // so there is no signed round-trip and no cast.
    llvm::DenseMap<mlir::Operation*, mlir::Value> _limitHandles;     // db.limit -> nl.limit handle

    // The handle a loop-opening or cross-product op carries, if it lies in some
    // limit's producing nest. Built by the pre-scan; the first (outermost,
    // program-order) limit to claim a shared producer wins, so a loop never needs
    // two handles. Absent (null on lookup) for a consumer loop, which fans out.
    llvm::DenseMap<mlir::Operation*, mlir::Value> _loopLimitHandle;  // db producer -> handle

    // A db.sort whose result is capped by an adjacent terminal db.limit fuses into
    // a bounded top-K: the count is baked into the nl.sort_buffer and the db.limit
    // becomes a pass-through. _sortTopK maps the fused db.sort to its bound;
    // _fusedLimits is the set of db.limits absorbed this way, so the limit pre-scan
    // and lowering skip them.
    llvm::DenseMap<mlir::Operation*, uint64_t> _sortTopK;   // db.sort -> top-K bound
    llvm::DenseSet<mlir::Operation*> _fusedLimits;          // db.limits fused into a sort

    void lowerOperation(mlir::Operation& operation);

    // Hoist one nl.limit handle per db.limit of @param region to the top of @param
    // hoistBlock and assign it to the loops producing the limited columns. A limit
    // inside a body run one row at a time belongs to that body, so only the limits
    // whose innermost such body is @param holder - none at function level - are taken.
    void hoistLimitHandles(mlir::Region& region, mlir::Block* hoistBlock, mlir::Operation* holder);

    // Lower one op of the system-command family - db.load_graph, db.change,
    // db.commit and their siblings - by copying it to its nl sibling at function
    // scope: same attributes, each db column result becoming the chunk the command
    // fills. False when the op is not one of them.
    bool lowerSystemCommand(mlir::Operation& operation);
    void lowerScanNodes(mlir::db::ScanNodes scanNodes);
    void lowerScanNodesByLabel(mlir::db::ScanNodesByLabel scanNodesByLabel);
    void lowerConstScanNodes(mlir::db::ConstScanNodes constScanNodes);
    void lowerScanNodesByPropertyValue(mlir::db::ScanNodesByPropertyValue scanNodesByPropertyValue);
    void lowerUnwindConst(mlir::db::UnwindConst unwindConst);
    void lowerLoadCSV(mlir::db::LoadCSV loadCSV);
    void lowerVectorSearch(mlir::db::VectorSearch vectorSearch);
    void lowerUnwind(mlir::db::Unwind unwind);
    void lowerMakeList(mlir::db::MakeList makeList);
    void lowerRange(mlir::db::Range range);

    // Lowers `[x IN xs WHERE p(x) | f(x)]`: the body is lowered into a region of its own
    // and the op built around it, since the type of the lists is the type of what that
    // body yields
    void lowerListComprehension(mlir::db::ListComprehension comprehension);
    void lowerScanEdges(mlir::db::ScanEdges scanEdges);
    void lowerScanEdgesByType(mlir::db::ScanEdgesByType scanEdgesByType);
    void lowerScanOutEdgesByLabelSrc(mlir::db::ScanOutEdgesByLabelSrc scanOutEdgesByLabelSrc);
    void lowerScanInEdgesByLabelTgt(mlir::db::ScanInEdgesByLabelTgt scanInEdgesByLabelTgt);
    void lowerScanOutEdgesByLabelTgt(mlir::db::ScanOutEdgesByLabelTgt scanOutEdgesByLabelTgt);
    void lowerScanInEdgesByLabelSrc(mlir::db::ScanInEdgesByLabelSrc scanInEdgesByLabelSrc);
    void lowerGetOutEdges(mlir::db::GetOutEdges getOutEdges);
    void lowerGetInEdges(mlir::db::GetInEdges getInEdges);
    void lowerGetEdges(mlir::db::GetEdges getEdges);
    void lowerGetOutEdgesByType(mlir::db::GetOutEdgesByType getOutEdgesByType);
    void lowerGetInEdgesByType(mlir::db::GetInEdgesByType getInEdgesByType);
    void lowerGetOutEdgesByLabel(mlir::db::GetOutEdgesByLabel getOutEdgesByLabel);
    void lowerGetInEdgesByLabel(mlir::db::GetInEdgesByLabel getInEdgesByLabel);
    void lowerGetNodeProperties(mlir::db::GetNodeProperties getNodeProperties);
    void lowerGetEdgeProperties(mlir::db::GetEdgeProperties getEdgeProperties);
    void lowerGetNodeLabelSet(mlir::db::GetNodeLabelSet getNodeLabelSet);
    void lowerGetEdgeTypes(mlir::db::GetEdgeTypes getEdgeTypes);
    void lowerCheckLabelConstraint(mlir::db::CheckLabelConstraint checkLabelConstraint);
    void lowerCheckEdgeTypeConstraint(mlir::db::CheckEdgeTypeConstraint checkEdgeTypeConstraint);
    void lowerCreateNode(mlir::db::CreateNode createNode);
    void lowerCreateEdge(mlir::db::CreateEdge createEdge);

    void lowerMerge(mlir::db::Merge merge);
    void lowerSetNodeProperty(mlir::db::SetNodeProperty setNodeProperty);
    void lowerSetEdgeProperty(mlir::db::SetEdgeProperty setEdgeProperty);
    void lowerDeleteNode(mlir::db::DeleteNode deleteNode);
    void lowerDeleteEdge(mlir::db::DeleteEdge deleteEdge);
    void lowerCrossProduct(mlir::db::CrossProduct product);
    void lowerHashJoin(mlir::db::HashJoin join);

    // Lowers each branch of a union in turn into the entry block, so the branches become
    // sibling loop nests run one after another. The nests share no chunk, so the state
    // the loop builders carry is dropped between them.
    void lowerUnion(mlir::db::Union unionOp);

    // Lowers a union with results - the body of a CALL - into branches that collect their
    // rows into one nl.union_buffer, drained by the loop the rest of the body lowers into
    void lowerUnionResults(mlir::db::Union unionOp);

    // Brings a union branch's result columns to the value type the whole result carries,
    // reaching them through @param resultColumns, what the branch's db.output or db.yield
    // names. The mappings it overwrites go into @param replacedMappings, for the caller to
    // restore once the operation is lowered: a column imported from outside the union is
    // read again after it.
    void convertUnionResultChunks(mlir::Operation& operation,
                                  mlir::OperandRange resultColumns,
                                  llvm::SmallVectorImpl<std::pair<mlir::Value, mlir::Value>>& replacedMappings);

    // Opens the one nl.distinct seen-set the branches of a deduping union record their
    // rows in, hoisted where every branch's filter can reach it
    void lowerDistinctSet(mlir::db::DistinctSet distinctSet);

    // Brings every branch's result columns to the one type each column of the result
    // carries, once the branches have been lowered and their types are known.
    // @param columnNames names the columns for a diagnostic, and is null where they have none.
    void reconcileBranchResultTypes(llvm::ArrayRef<mlir::MutableOperandRange> branchColumns,
                                    mlir::ArrayAttr columnNames);

    mlir::Type unionResultType(llvm::ArrayRef<mlir::MutableOperandRange> branchColumns,
                               size_t columnIndex,
                               mlir::ArrayAttr columnNames);

    void throwOnDisagreeingBranchTypes(mlir::Type branchType,
                                       mlir::Type resultType,
                                       mlir::ArrayAttr columnNames,
                                       size_t columnIndex);

    // Reads the null literal's chunk as a column of @param chunkType, holding one absent
    // value per row of it
    mlir::Value typedNullChunk(mlir::Value chunk, mlir::Type chunkType);

    // Lower a db.optional_match into an nl.optional_buffer, the pattern's own loop nest,
    // an nl.optional_collect at its deepest point and an nl.optional_drain loop yielding
    // the matched rows then one null-padded row per input row the pattern missed. A
    // pipeline breaker like db.sort, but its accumulator covers one step, not the relation.
    void lowerOptionalMatch(mlir::db::OptionalMatch optionalMatch);

    // Lower a db.exists_subquery into an nl.exists_buffer, the body's own loop nest ending
    // in an nl.exists_mark, and the nl.exists_result that reads the flags back as the
    // boolean the op stands for. A body that cannot carry the rows it was given runs under
    // a loop over them, which the rest of the query then goes on inside.
    void lowerExistsSubquery(mlir::db::ExistsSubquery exists);

    // Lower a db.call_subquery. A body carrying its scope, and a unit body, are lowered in
    // place: the block arguments become the step's chunks, the body's loops nest in the
    // step block, and the yielded chunks are what the results map to. A returning body
    // that carries nothing runs one input row at a time instead, see lowerSubqueryPerRow.
    void lowerCallSubquery(mlir::db::CallSubquery call);

    // Lower the body of a db.call_subquery rooted in @param stepBlock, mapping each block
    // argument to the chunk @param inputChunks holds for it, and fill @param yieldedChunks
    // with the chunks the body's db.subquery_yield names and @param yieldedTag with the
    // tag it names, null when it names none.
    void lowerSubqueryBody(mlir::db::CallSubquery call,
                           mlir::Block* stepBlock,
                           llvm::ArrayRef<mlir::Value> inputChunks,
                           llvm::SmallVectorImpl<mlir::Value>& yieldedChunks,
                           mlir::Value& yieldedTag);

    // Lower an optional db.call_subquery: the body - run in place or one row at a time,
    // as lowerCallSubquery would run it - feeds an nl.optional_buffer, nl.optional_collect
    // and nl.optional_drain around it, so an input row the body yields nothing for comes
    // back once with the body's columns null.
    void lowerOptionalSubquery(mlir::db::CallSubquery call,
                               mlir::Block* stepBlock,
                               llvm::ArrayRef<mlir::Value> inputChunks);

    // Lower a returning body that carries nothing: an nl.each_row over the step's input
    // chunks drives the body once per input row, every accumulator of the body resets in
    // that step, and the row's own chunks are crossed with what the body yields.
    void lowerSubqueryPerRow(mlir::db::CallSubquery call,
                             mlir::Block* stepBlock,
                             llvm::ArrayRef<mlir::Value> inputChunks);

    // The most deeply nested block any of @param chunks is bound in, or @param fallback
    // when they are all bound at or above it: where an op reading them all belongs
    static mlir::Block* deepestOwnerBlock(llvm::ArrayRef<mlir::Value> chunks, mlir::Block* fallback);

    // Lays the constant out over the rows of its driver, the layout rowAlignedChunk
    // performs for every consumer that reads a constant per row
    void lowerBroadcastConstant(mlir::db::BroadcastConstant broadcast);
    void lowerLimit(mlir::db::Limit limit);
    void lowerSkip(mlir::db::Skip skip);

    // Find db.sort results capped by an adjacent terminal db.limit (the
    // ORDER BY ... LIMIT k shape) and record the fusion: the sort is the limit's
    // sole consumer and every limit column comes from it. Fills _sortTopK and
    // _fusedLimits so the limit pre-scan skips the fused limit (no nl.limit
    // handle, no producing-loop early-exit - top-K must scan every row), lowerSort
    // bakes the count into the nl.sort_buffer, and lowerLimit passes through.
    void detectTopKFusion(mlir::func::FuncOp dbFunction);

    // Lower a db.sort: hoist an nl.sort_buffer accumulator (carrying the key
    // spec) to the top of the entry block, place an nl.sort_collect in the
    // innermost producing loop body to append each chunk, then - after the
    // producing loop - emit an nl.sort source iterator and an nl.for over it that
    // yields the sorted rows. db.sort's results map to that emit loop's
    // variables, so the db.output that follows lowers into the emit loop body.
    void lowerSort(mlir::db::Sort sort);

    // Lower a db.remove_duplicates: hoist an nl.distinct seen-set handle to the
    // top of the entry block, then place an nl.distinct_filter in the innermost
    // producing loop body that emits each step's not-yet-seen rows as fresh
    // chunks. db.remove_duplicates' results map to those survivor chunks, so its
    // consumer - nl.output, or a downstream traversal when chained - reads the
    // deduped rows. It opens no loop of its own (a streaming filter, unlike the
    // pipeline-breaking db.sort), so the limit machinery bounds it unchanged: a
    // db.limit over its results reaches the real producing loops through
    // assignProducerLoops' operand recursion and early-exits them.
    void lowerRemoveDuplicates(mlir::db::RemoveDuplicates distinct);

    // Lower a db.count: hoist an nl.count tally to the top of the entry block,
    // place an nl.count_update in the innermost producing loop body to charge each
    // chunk's non-null rows, then - after the producing loop - an nl.count_result
    // that materializes the single tally row (an unsigned i64, !nl.chunk<ui64>) at
    // function scope. db.count's result maps to that chunk, so the db.output that
    // follows lowers into a function-scope nl.output reading it. A pipeline breaker
    // like db.sort, but it collapses to one row, so it opens no emit loop. A
    // `distinct` count adds the DISTINCT pair around the update - a hoisted
    // nl.distinct seen-set and an nl.distinct_filter cutting the chunk ahead of the
    // update - so the tally charges each distinct value once.
    void lowerCount(mlir::db::Count count);

    // Lower a db.count_scan_rows: the tally is already known from the graph's node counts,
    // so there is no relation to walk and no accumulator to thread. Emit one
    // nl.count_scan_rows carrying the same label conjunctions, hoisted to the top of the
    // entry block the way a constant is, which materializes the single tally row (an
    // unsigned i64, !nl.chunk<ui64>) the db result maps to.
    void lowerCountScanRows(mlir::db::CountScanRows countScanRows);

    // Lower a db.sum / db.min / db.max / db.avg: the value-reducing siblings of
    // lowerCount. The db op names the reduction (`kind`); the input and result SSA
    // values are the column being reduced and the single-row result. Hoist an
    // nl.aggregate accumulator to the top of the entry block, place an
    // nl.aggregate_update in the innermost producing loop body to fold each chunk's
    // non-null values, then - after the loop - an nl.aggregate_result that
    // materializes the single reduced row as a nullable value chunk at function
    // scope. The db result maps to that chunk. The accumulator element type (and thus
    // the result value type) follows Cypher: avg widens to f64, sum/min/max keep the
    // input's value type; sum/avg require a numeric column and min/max an orderable
    // one, so a string sum or an embedding min is rejected here. A `distinct`
    // reduction adds the DISTINCT pair around the update - a hoisted nl.distinct
    // seen-set and an nl.distinct_filter cutting the chunk ahead of the update - so
    // each distinct value is reduced once.
    void lowerAggregate(mlir::Value input,
                        mlir::Value result,
                        mlir::storage::AggregateKind kind,
                        bool distinct);

    // Hoists an nl.constant to the top of the entry block
    void lowerConstant(mlir::db::ConstantOp constant);

    // Hoists an nl.const_list to the top of the entry block, the way a scalar constant is
    // hoisted; its chunk keeps the db column's list element type

    enum class BinaryResultKind {
        Numeric,   // add/sub/mul/div/mod: promoted numeric, nullable if either operand is
        Boolean,   // eq/neq/gt/lt/gte/lte and and/or/xor: i1, nullable if either is
        Double,    // pow: always f64 per openCypher, nullable if either operand is
        Concat,    // concat: string or list (determined at lowering)
        Index,     // index: a nullable tagged scalar, whatever the list holds
        Membership, // in: a nullable i1, since a list element can be null
    };

    template <typename NLOp>
    void lowerBinaryOp(mlir::Operation& op, BinaryResultKind kind);

    // The result chunk element type for a binary op of this kind over these operand
    // chunk types: a promoted numeric or an i1, wrapped nullable as the kind dictates.
    mlir::Type binaryResultElement(BinaryResultKind kind, mlir::Type lhsType, mlir::Type rhsType);

    // Propagates nullity from operand to result
    void lowerNot(mlir::db::NotOp notOp);

    // Lower a db.case into its nl sibling: resolve the one value column its branches
    // share, convert the branches that need promoting into it, and place the selection
    // where every condition and value it reads is bound.
    void lowerCase(mlir::db::Case caseOp);

    // The value element type a CASE's branches share: the one they all carry, the
    // promotion of their numbers when they carry two, and an i64 when every branch is
    // null. A branch no value column can hold is rejected here.
    mlir::Type caseResultElement(llvm::ArrayRef<mlir::Value> valueChunks);

    // @param chunk as the selection reads it: itself when it already carries
    // @param resultElement, and an nl.to_float / nl.to_integer of it when the branches
    // promoted past its own type. A null branch is left untyped.
    mlir::Value caseBranchChunk(mlir::Value chunk, mlir::Type resultElement);

    void lowerUnaryFunction(mlir::Operation* op);

    void lowerBinaryFunction(mlir::Operation* op);

    void setInsertionForUnaryOp(mlir::Value operandChunk);

    // Applies a mask to a carry set
    void lowerFilter(mlir::db::FilterOp filter);

    // Lower a db.group_aggregate: the grouped, multi-row sibling of lowerAggregate,
    // modeled on lowerSort. Hoist an nl.group_aggregate_buffer accumulator (carrying
    // keyCount and the aggregate kinds) to the top of the entry block, place an
    // nl.group_aggregate_update in the innermost producing loop body to fold each
    // chunk into the per-group state, then - after the producing loop - emit an
    // nl.group_aggregate source iterator and an nl.for over it that yields one row
    // per group. db.group_aggregate's results (the grouping-key columns then the
    // aggregate results) map to that emit loop's variables, so the db.output that
    // follows lowers into the emit loop body. The aggregate result chunk types are
    // resolved here from each kind and its input column: a ui64 for count, the
    // input's value type for sum/min/max, f64 for avg; a sum/min/max/avg requires a
    // property value column (an ID column is rejected), so a grouped sum of node IDs
    // is caught here.
    void lowerGroupAggregate(mlir::db::GroupAggregate groupAggregate);

    // Lower a db.collect: hoist an nl.collect_buffer above the loops, emit an
    // nl.collect_update in the producing loop, and drain the filled accumulator with an
    // nl.collect source (one row per group, a list cell) plus its nl.for.
    void lowerCollect(mlir::db::Collect collect);

    // Lower a db.unwind_collect (the fused collect-then-unwind): the same accumulate
    // phase as lowerCollect, but drained by an nl.unwind_collect source (one row per collected
    // element) plus its nl.for - the list never materializes.
    void lowerUnwindCollect(mlir::db::UnwindCollect unwindCollect);

    void lowerShortestPath(mlir::db::ShortestPath shortestPath);

    void lowerCallProcedure(mlir::db::CallProcedure call);

    // Emits the nl.output the sink reads this result off, and hands it back: a union
    // reaches for it again once every branch has said what its columns hold
    mlir::nl::Output lowerOutput(mlir::db::Output output);

    // Lower one factor region of a db.cross_product or a db.hash_join into a loop
    // nest rooted at rootBlock, collecting its db.yield columns (mapped to their nl
    // chunks) in yieldedChunks and returning the factor's innermost loop body -
    // where the cross product, the probe, or a deeper factor nests.
    mlir::Block* lowerFactor(mlir::Region& factor,
                             mlir::Block* rootBlock,
                             llvm::SmallVectorImpl<mlir::Value>& yieldedChunks);

    // Wrap an nl source op's iterator in an nl.for and bind each db result
    // column to the matching loop variable
    void buildLoopForSource(mlir::Value iterator, mlir::Operation* dbOp);

    // Walk the db dataflow backward from a limited column, recording in
    // _loopLimitHandle that each loop-opening op (scan / get_out_edges) and cross
    // product it depends on carries this limit's handle.
    // A cross product's factors are regions, so it recurses through their
    // db.yield operands; a property fetch opens no loop but is traversed to reach
    // its input chunk's loop. The first limit to claim a producer keeps it.
    // Returns whether the walk reached a loop at all: a column computed from constants
    // alone is produced by none, which is what sends the handle to the driving relation.
    // @param rowsDroppedBeforeTheCut is set once the walk has passed an op that
    // drops rows, which bars the handle from a cross product below it.
    bool assignProducerLoops(mlir::Value column,
                             mlir::Value handle,
                             bool rowsDroppedBeforeTheCut,
                             mlir::Operation* holder);

    // Records that the loops producing the relation which drives @param limit's projection
    // carry its handle, so a cut charged to constants alone stops its nest as any other
    // cut does rather than letting it run to the end.
    void assignCardinalityDriverLoop(mlir::db::Limit limit, mlir::Value handle, mlir::Operation* holder);

    // Peephole over the lowered nl function: where an nl.limit_truncate's results
    // are consumed exactly by one adjacent nl.output (the terminal-LIMIT shape),
    // fold the pair into a single nl.output that carries the limit handle and
    // emits the budgeted prefix directly, dropping the truncate's copy. Chained
    // and mixed cases do not match and keep their truncate.
    void foldTruncatesIntoOutputs(mlir::func::FuncOp nlFunction);
    void foldSkipTruncatesIntoOutputs(mlir::func::FuncOp nlFunction);

    // The procedure registered under this full name, or a clear error when there is
    // no registry to resolve it against or no procedure of that name
    const Procedure* procedureFor(llvm::StringRef name) const;

    // The nl.get_property_type handle for a property name, inserted once at the
    // top of the entry block (above every loop) and reused on later lookups
    mlir::Value getOrCreatePropertyTypeHandle(llvm::StringRef propertyName);

    // The nl.get_edge_type_set handle for a set of edge type names, inserted once at
    // the top of the entry block (above every loop) and reused on later lookups - the
    // edge sibling of getOrCreatePropertyTypeHandle
    mlir::Value getOrCreateEdgeTypeSetHandle(mlir::ArrayAttr edgeTypeNames);

    static mlir::Type columnType(mlir::Value column);

    // The !nl.chunk<!storage.nullable<T>> a fetch of this property produces, with T the
    // value type the name resolves to in the schema, or the one the read declares
    mlir::Type propertyValueChunkType(llvm::StringRef propertyName, mlir::Type declared);

    // Point the builder just before the terminator of block, where the next
    // lowered op belongs
    void setInsertionInto(mlir::Block* block);

    // Point the builder at the end of the entry block's run of hoisted constants, where
    // the next one belongs
    void setInsertionAfterHoistedConstants();

    // Point the builder at the very top of the entry block, above the constants hoisted
    // there
    void setInsertionToEntryBlockStart();

    // The chunks one group of a db op's column operands lowered to, in order
    void mapColumns(mlir::OperandRange columns, llvm::SmallVectorImpl<mlir::Value>& chunks);

    // The chunk an optional mask operand lowered to, or a null Value for an absent one -
    // which is what the nl op then carries in its place
    mlir::Value mapOptionalMask(mlir::Value mask);

    // Point the builder just after the loop nest that @param updateBlock belongs to,
    // where an accumulator filled from that block holds its final value. A drain loop
    // lowered before this one sits further down the entry block and may read the
    // result, so the end of the entry block is too late a home for it.
    void setInsertionAfterProducingLoop(mlir::Block* updateBlock);

    // Point the builder at the right place for an op consuming lhs and rhs.
    void setInsertionForBinaryOp(mlir::Value lhs, mlir::Value rhs);

    // The n-ary sibling of setInsertionForBinaryOp, for an op reading a whole set of
    // columns - the branches of a db.case
    void setInsertionForNaryOp(llvm::ArrayRef<mlir::Value> operands);

    // Lays the constants among the chunks an accumulator buffers over the rows of the
    // driving relation, or over the single row they stand for where none drives the step.
    // A buffer appends rows, and a constant carries none of its own.
    void rowAlignBufferedChunks(llvm::SmallVectorImpl<mlir::Value>& chunks);

    // Lays the constants among the chunks a cut is charged to over the rows of the
    // driving relation. A cut walks rows and a constant carries none of its own - it
    // holds one value standing for every row of the step - so the loop's rows are the
    // count a cut over constants alone charges, and the count every cut chained after it
    // reads in turn.
    void rowAlignCutChunks(llvm::SmallVectorImpl<mlir::Value>& chunks);

    // Lays the constants among a hash join factor's yielded chunks over the rows that
    // factor walks. The build side appends its chunks to growing buffers and the probe
    // gathers both sides by matched row, so neither can read a chunk holding one value
    // for every row rather than a row of its own.
    void rowAlignFactorChunks(llvm::SmallVectorImpl<mlir::Value>& chunks);

    // The chunk whose rows the constants of a step are laid out over: the first of
    // @param chunks carrying rows of its own, and the innermost loop's cardinality when
    // every one of them is a constant, or there are none.
    mlir::Value cardinalityDriver(llvm::ArrayRef<mlir::Value> chunks) const;

    // Follows the cardinality driver through a step that narrows the relation, from the
    // chunk it read in @param inputChunks to the narrowed chunk standing for it in
    // @param resultChunks. The driver stands for the relation a projection of constants
    // alone is a projection of, so leaving it on the wider chunk would size that
    // emission by the rows the step dropped.
    void followCardinalityThrough(mlir::ValueRange inputChunks, mlir::ValueRange resultChunks);

    // The chunk a step that walks rows is handed for @param chunk: itself when it
    // carries rows, and its value laid out over the rows of @param cardinality - the
    // driving relation's chunk, null when no relation drives the projection - when it
    // is a constant, which holds one value standing for every row and so has no rows
    // of its own to walk.
    mlir::Value rowAlignedChunk(mlir::Value chunk, mlir::Value cardinality);

    mlir::Value nullableValueChunk(mlir::Value chunk);

    mlir::Value unionColumnChunk(mlir::Value chunk);

    // The shape @param chunk must take for a drain to pad a missed row of it with null,
    // or the chunk itself where it already spells one
    mlir::Value paddedColumnChunk(mlir::Value chunk);

    mlir::Value nullableListChunk(mlir::Value chunk);

    // Builds the nl.to_nullable that wraps @param chunk's rows in @param valueElement's
    // nullable column, which the value and the list siblings above share
    mlir::Value toNullableChunk(mlir::Value chunk, mlir::Type valueElement);

    mlir::Value ownedStringColumnChunk(mlir::Value chunk);

    // The chunk element type an unwind of @param sourceElement produces: a drained list
    // gives up the type its own elements carry, falling back to the type-erased
    // list_element when they share none, and any other source keeps its own element,
    // its cells being the elements themselves
    static mlir::Type unwoundElementType(mlir::MLIRContext* context, mlir::Type sourceElement);

    // The element type of the lists @param chunks build: the one type every chunk carries,
    // falling back to the type-erased list_element when they carry no single one - the
    // homogeneity verdict taken over the resolved chunks rather than over the db columns
    static mlir::Type listedElementType(mlir::MLIRContext* context, llvm::ArrayRef<mlir::Value> chunks);

    // The nl chunk a db value lowered to, and the block that holds a chunk
    mlir::Value mapValue(mlir::Value dbValue) const;
    static mlir::Block* ownerBlock(mlir::Value chunkValue);

    // Whether @param inner is @param outer or lies in a region nested in it
    static bool enclosesBlock(mlir::Block* outer, mlir::Block* inner);

    // The deeper of two blocks: the one the other encloses. Blocks where neither encloses
    // the other hold no chunks one op can read, so that is an error rather than a choice
    static mlir::Block* deeperOfBlocks(mlir::Block* first, mlir::Block* second);

    // Where an accumulator filled from @param producingBlock is updated. A chunk bound
    // above the root is loop-invariant - a hoisted constant layout, a metadata tally - and
    // the accumulator it feeds lives in the root, so it is charged there instead.
    mlir::Block* accumulatorUpdateBlock(mlir::Block* producingBlock) const;

    // The chunk of @param chunks bound deepest - the one whose block every other is
    // valid in, which is where an op reading all of them belongs. A null Value for an
    // empty range, which is an op reading no chunk at all.
    mlir::Value deepestBoundChunk(llvm::ArrayRef<mlir::Value> chunks);

    // Find the first place where both @param first and @param second are valid
    mlir::Block* deeperBlock(mlir::Value first, mlir::Value second);
};

}
