#pragma once

#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"

#include "DBOps.h"

namespace db {

class GraphView;

// Lowers a function in the db dialect into a function in the nl dialect.
//
// The db dialect describes a query as column dataflow: db.scan_nodes
// produces a column, each db.get_out_edges consumes columns and produces more,
// and db.output names the result projection.
//
// The nl dialect makes execution explicit: every column becomes a column chunk
// generated by an nl.for loop. Every db op that produces columns
// becomes an nl iterator wrapped in a for loop.
//
// Lowering turns the flat db dataflow into a loop nest:
//
//   db.scan_nodes / db.get_out_edges  ->  nl source op + nl.for over its chunks
//   db.output                          ->  nl.output inside the binding loop
//   db.limit                           ->  a hoisted nl.limit handle, a `limit`
//                                          operand on the loops that produce its
//                                          columns, an nl.limit_update, and an
//                                          nl.limit_truncate that copies the prefix
//                                          just before the consumer (nl.output when
//                                          unchained, the inner query when chained)
//   db.skip                            ->  a hoisted nl.skip handle, an
//                                          nl.skip_update, and an nl.skip_truncate
//                                          that lifts the surviving suffix just
//                                          before the consumer. No loop operand (a
//                                          skip cannot early-exit). When unchained,
//                                          the truncate folds into a skip-bearing
//                                          nl.output that emits the suffix in place
//                                          at an offset; the copy survives only for
//                                          a chained suffix (reads from row zero)
//
// db.get_node_properties / db.get_edge_properties resolve their property name
// against the graph schema here (hence the GraphView): the name is hoisted into
// one nl.get_property_type above the loops, and the concrete value type is baked
// into the nullable value chunk the fetch produces inside the binding loop.
//
// db.cross_product lowers to two nested factor loop nests - the inner factor's
// loops nested inside the outer factor's innermost loop body, so the inner
// factor re-runs once per outer chunk (a nested-loop join, bounded memory) -
// bridged at the deepest point by an nl.cross_product that crosses the two
// factors' yielded chunks just before db.output consumes them.
//
class DBLowering {
public:
    DBLowering(mlir::MLIRContext* context, const GraphView* view);
    ~DBLowering();

    // Translate a FuncOp in db dialect to nl dialect
    mlir::func::FuncOp lower(mlir::func::FuncOp dbFunction, mlir::ModuleOp module);

private:
    mlir::OpBuilder _builder;

    // Graph schema, used to resolve a property name to its value type
    const GraphView* _view {nullptr};

    // db column SSA value -> the nl chunk
    llvm::DenseMap<mlir::Value, mlir::Value> _valueMap;

    // Property name -> the hoisted nl.get_property_type handle, so a name is
    // resolved once and shared by every fetch that reads it
    llvm::StringMap<mlir::Value> _propertyTypes;

    // Entry block of the nl function being built
    mlir::Block* _entryBlock {nullptr};

    // The block a root scan opens its loop in. It is the entry block at top
    // level, but a db.cross_product lowers its inner factor with the outer
    // factor's innermost loop body as the root, so the inner factor's scans
    // nest inside the outer loop (the nested-loop join).
    mlir::Block* _rootBlock {nullptr};

    // The body of the most recent loop buildLoopForSource opened. A factor's
    // dataflow is linear and each loop nests inside the previous, so the last
    // loop opened is the factor's innermost one; lowerFactor reads this once the
    // factor is lowered to root the inner factor there and to place the cross
    // product at that deepest point. Not an insertion cursor - the builder is
    // not left in the loop body - just a record of which block is innermost.
    mlir::Block* _innermostLoopBody {nullptr};

    // Each db.limit gets its own hoisted nl.limit handle - N independent budgets.
    // A pre-scan in lower() finds every db.limit before any loop is built, so the
    // handles exist first to be threaded into the loops as they are created. The
    // count is unsigned end to end (UI64Attr accessor -> NLLimitState's size_t),
    // so there is no signed round-trip and no cast.
    llvm::DenseMap<mlir::Operation*, mlir::Value> _limitHandles;     // db.limit -> nl.limit handle

    // The handle a loop-opening or cross-product op carries, if it lies in some
    // limit's producing nest. Built by the pre-scan; the first (outermost,
    // program-order) limit to claim a shared producer wins, so a loop never needs
    // two handles. Absent (null on lookup) for a consumer loop, which fans out.
    llvm::DenseMap<mlir::Operation*, mlir::Value> _loopLimitHandle;  // db producer -> handle

    // A db.sort whose result is capped by an adjacent terminal db.limit fuses into
    // a bounded top-K: the count is baked into the nl.sort_buffer and the db.limit
    // becomes a pass-through. _sortTopK maps the fused db.sort to its bound;
    // _fusedLimits is the set of db.limits absorbed this way, so the limit pre-scan
    // and lowering skip them.
    llvm::DenseMap<mlir::Operation*, uint64_t> _sortTopK;   // db.sort -> top-K bound
    llvm::DenseSet<mlir::Operation*> _fusedLimits;          // db.limits fused into a sort

    void lowerOperation(mlir::Operation& operation);
    void lowerScanNodes(mlir::db::ScanNodes scanNodes);
    void lowerGetOutEdges(mlir::db::GetOutEdges getOutEdges);
    void lowerGetInEdges(mlir::db::GetInEdges getInEdges);
    void lowerGetNodeProperties(mlir::db::GetNodeProperties getNodeProperties);
    void lowerGetEdgeProperties(mlir::db::GetEdgeProperties getEdgeProperties);
    void lowerCrossProduct(mlir::db::CrossProduct product);
    void lowerLimit(mlir::db::Limit limit);
    void lowerSkip(mlir::db::Skip skip);

    // Find db.sort results capped by an adjacent terminal db.limit (the
    // ORDER BY ... LIMIT k shape) and record the fusion: the sort is the limit's
    // sole consumer and every limit column comes from it. Fills _sortTopK and
    // _fusedLimits so the limit pre-scan skips the fused limit (no nl.limit
    // handle, no producing-loop early-exit - top-K must scan every row), lowerSort
    // bakes the count into the nl.sort_buffer, and lowerLimit passes through.
    void detectTopKFusion(mlir::func::FuncOp dbFunction);

    // Lower a db.sort: hoist an nl.sort_buffer accumulator (carrying the key
    // spec) to the top of the entry block, place an nl.sort_collect in the
    // innermost producing loop body to append each chunk, then - after the
    // producing loop - emit an nl.sort source iterator and an nl.for over it that
    // yields the sorted rows. db.sort's results map to that emit loop's
    // variables, so the db.output that follows lowers into the emit loop body.
    void lowerSort(mlir::db::Sort sort);

    void lowerOutput(mlir::db::Output output);

    // Lower one factor region of a db.cross_product into a loop nest rooted at
    // rootBlock, collecting its db.yield columns (mapped to their nl chunks) in
    // yieldedChunks and returning the factor's innermost loop body - where the
    // cross product, or a deeper factor, nests.
    mlir::Block* lowerFactor(mlir::Region& factor,
                             mlir::Block* rootBlock,
                             llvm::SmallVectorImpl<mlir::Value>& yieldedChunks);

    // Wrap an nl source op's iterator in an nl.for and bind each db result
    // column to the matching loop variable
    void buildLoopForSource(mlir::Value iterator, mlir::Operation* dbOp);

    // Walk the db dataflow backward from a limited column, recording in
    // _loopLimitHandle that each loop-opening op (scan / get_out_edges) and cross
    // product it depends on carries this limit's handle.
    // A cross product's factors are regions, so it recurses through their
    // db.yield operands; a property fetch opens no loop but is traversed to reach
    // its input chunk's loop. The first limit to claim a producer keeps it.
    void assignProducerLoops(mlir::Value column, mlir::Value handle);

    // Peephole over the lowered nl function: where an nl.limit_truncate's results
    // are consumed exactly by one adjacent nl.output (the terminal-LIMIT shape),
    // fold the pair into a single nl.output that carries the limit handle and
    // emits the budgeted prefix directly, dropping the truncate's copy. Chained
    // and mixed cases do not match and keep their truncate.
    void foldTruncatesIntoOutputs(mlir::func::FuncOp nlFunction);
    void foldSkipTruncatesIntoOutputs(mlir::func::FuncOp nlFunction);

    // The nl.get_property_type handle for a property name, inserted once at the
    // top of the entry block (above every loop) and reused on later lookups
    mlir::Value getOrCreatePropertyTypeHandle(llvm::StringRef propertyName);

    // The !nl.chunk<!nl.nullable<T>> a fetch of this property produces, with T
    // the value type the name resolves to in the schema
    mlir::Type propertyValueChunkType(llvm::StringRef propertyName);

    // Point the builder just before the terminator of block, where the next
    // lowered op belongs
    void setInsertionInto(mlir::Block* block);

    // The nl chunk a db value lowered to, and the block that holds a chunk
    mlir::Value mapValue(mlir::Value dbValue) const;
    static mlir::Block* ownerBlock(mlir::Value chunkValue);
};

}
