#pragma once

#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"

#include "DBOps.h"

namespace db {

class GraphView;

// Lowers a function in the db dialect into a function in the nl dialect.
//
// The db dialect describes a query as column dataflow: db.scan_nodes
// produces a column, each db.get_out_edges consumes columns and produces more,
// and db.output names the result projection.
//
// The nl dialect makes execution explicit: every column becomes a column chunk
// generated by an nl.for loop. Every db op that produces columns
// becomes an nl iterator wrapped in a for loop.
//
// Lowering turns the flat db dataflow into a loop nest:
//
//   db.scan_nodes / db.get_out_edges  ->  nl source op + nl.for over its chunks
//   db.output                          ->  nl.output inside the binding loop
//
// db.get_node_properties / db.get_edge_properties resolve their property name
// against the graph schema here (hence the GraphView): the name is hoisted into
// one nl.get_property_type above the loops, and the concrete value type is baked
// into the nullable value chunk the fetch produces inside the binding loop.
//
class DBLowering {
public:
    DBLowering(mlir::MLIRContext* context, const GraphView* view);
    ~DBLowering();

    // Translate a FuncOp in db dialect to nl dialect
    mlir::func::FuncOp lower(mlir::func::FuncOp dbFunction, mlir::ModuleOp module);

private:
    mlir::OpBuilder _builder;

    // Graph schema, used to resolve a property name to its value type
    const GraphView* _view {nullptr};

    // db column SSA value -> the nl chunk
    llvm::DenseMap<mlir::Value, mlir::Value> _valueMap;

    // Property name -> the hoisted nl.get_property_type handle, so a name is
    // resolved once and shared by every fetch that reads it
    llvm::StringMap<mlir::Value> _propertyTypes;

    // Entry block of the nl function being built
    mlir::Block* _entryBlock {nullptr};

    void lowerOperation(mlir::Operation& operation);
    void lowerScanNodes(mlir::db::ScanNodes scanNodes);
    void lowerGetOutEdges(mlir::db::GetOutEdges getOutEdges);
    void lowerGetNodeProperties(mlir::db::GetNodeProperties getNodeProperties);
    void lowerGetEdgeProperties(mlir::db::GetEdgeProperties getEdgeProperties);
    void lowerOutput(mlir::db::Output output);

    // Wrap an nl source op's iterator in an nl.for and bind each db result
    // column to the matching loop variable
    void buildLoopForSource(mlir::Value iterator, mlir::Operation* dbOp);

    // The nl.get_property_type handle for a property name, inserted once at the
    // top of the entry block (above every loop) and reused on later lookups
    mlir::Value getOrCreatePropertyTypeHandle(llvm::StringRef propertyName);

    // The !nl.chunk<!nl.nullable<T>> a fetch of this property produces, with T
    // the value type the name resolves to in the schema
    mlir::Type propertyValueChunkType(llvm::StringRef propertyName);

    // Point the builder just before the terminator of block, where the next
    // lowered op belongs
    void setInsertionInto(mlir::Block* block);

    // The nl chunk a db value lowered to, and the block that holds a chunk
    mlir::Value mapValue(mlir::Value dbValue) const;
    static mlir::Block* ownerBlock(mlir::Value chunkValue);
};

}
