name: CI Full Matrix Build

on:
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 0 * * *'
    - cron: '0 16 * * *'
    - cron: '0 21 * * *'
  workflow_dispatch:


jobs:
  build:
    uses: ./.github/workflows/ci_build.yml
    with:
      os_list: '["ubuntu-22.04", "ubuntu-24.04", "macos-14-xlarge", "macos-15-xlarge", "macos-26-xlarge"]'
      python_version_list: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
    secrets: inherit

