name: CI Full Matrix Build

on:
  workflow_dispatch:


jobs:
  matrix:
    uses: ./.github/workflows/ci_release_matrix.yml

  build:
    needs: matrix
    uses: ./.github/workflows/ci_build.yml
    with:
      os_list: ${{ needs.matrix.outputs.os_list }}
      python_version_list: ${{ needs.matrix.outputs.python_version_list }}
    secrets: inherit

