name: CI Release Matrix

on:
  workflow_call:
    outputs:
      os_list:
        value: ${{ jobs.matrix.outputs.os_list }}
      python_version_list:
        value: ${{ jobs.matrix.outputs.python_version_list }}


jobs:
  matrix:
    runs-on: ubuntu-24.04-turing
    outputs:
      os_list: '["ubuntu-22.04-turing", "ubuntu-24.04-turing", "ubuntu-22.04-arm", "ubuntu-24.04-arm", "macos15", "macos26"]'
      python_version_list: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
    steps:
      - run: echo "Defining matrix"
